name: acanvas_physics
version: 0.11.0
description: Port of Box2DFlash v2.1a to StageXL/Dart.
environment:
  sdk: '>=2.0.0-dev.55.0 <3.0.0'

dependencies:
  stagexl: '>=1.4.0 <2.0.0'

dev_dependencies:
  build_runner: '>=0.10.0 <2.0.0'
  build_test: '>=0.10.2+5 <2.0.0'
  build_web_compilers: '>=0.4.0+4 <2.0.0'