name: acanvas_physics
version: 0.10.0-dev
description: Port of Box2DFlash v2.1a to StageXL/Dart.
environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  stagexl:
     version: 1.3.2-dev
     git: https://github.com/bp74/StageXL
  logging: any

dev_dependencies:
  #-------- Dart 2.0.0-dev --------
  build_runner: ^0.8.9
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0+3